Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.projects.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.users.urls')),

    # urls para ckeditor
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/projects/urls.py
from django.urls import path
from . import views

app_name = "projects_app"

urlpatterns = [
    path(
        "projects/",
        views.ProjectsListView.as_view(),
        name="projects-list",
    ),
    path(
        "projects/<pk>/",
        views.ProjectsDetailView.as_view(),
        name="project-detail",
    )


]

applications/projects/models.py
#from typing_extensions import Required
from django.db import models
from django.conf import settings
from django.db.models.deletion import CASCADE
from ckeditor_uploader.fields import RichTextUploadingField

from .managers import ProjectsManager

# Create your models here.

class hardware(models.Model):
    """Model definition for Hardware."""

    # TODO: Define fields here
    name = models.CharField(
        'nombre', 
        max_length=20,
        unique=True,
        blank=False, 
        null=False
        )
    class Meta:
        """Meta definition for Hardware."""

        verbose_name = 'Hardware'
        verbose_name_plural = 'Hardware'

    def __str__(self):
        """Unicode representation of Hardware."""
        return f"{self.id} | {self.name}"

class languages(models.Model):
    """Model definition for Languages."""

    name = models.CharField(
        'nombre', 
        max_length=20,
        unique=True,
        blank=False, 
        null=False
        )
    typed = models.BooleanField(
        'Tipado',
        blank=False,
        null = False
        )
    class Meta:
        """Meta definition for Languages."""

        verbose_name = 'Lenguaje'
        verbose_name_plural = 'Lenguajes'

    def __str__(self):
        """Unicode representation of Languages."""
        return f"{self.id} | {self.name}"

class framework(models.Model):
    """Model definition for Frameworks."""

    # TODO: Define fields here
    name = models.CharField(
        'nombre', 
        max_length=20,
        unique=True,
        blank=False, 
        null=False
        )
    class Meta:
        """Meta definition for Framework."""

        verbose_name = 'Framework'
        verbose_name_plural = 'Frameworks'

    def __str__(self):
        """Unicode representation of Frameworks."""
        return f"{self.id} | {self.name}"



class projects(models.Model):
    # Variables categorías
    HardwareDevelop = "1"
    SoftwareDevelop = "2"
    DataSciece = "3"
    MachineLearning = "4"
    ArtificialInteligence = "5"


    #
    CATEGORY_CHOICES = (
        (HardwareDevelop, "Hardware Development"),
        (SoftwareDevelop, "Software Development"),
        (DataSciece, "Data Science"),
        (MachineLearning, "Machine Learning"),
        (ArtificialInteligence, "Artificial Inteligence")
    )

    title = models.CharField(
        "Title", 
        max_length=200, 
        null=False, 
        unique=True
        )
    category = models.CharField(
        "Category", 
        max_length=1,
        choices=CATEGORY_CHOICES
        )
    date = models.DateField(
        "Date", 
        auto_now=False, 
        auto_now_add=False
        )
    resume = models.TextField(
        "Resume",
        max_length=200
        )
    contenido = RichTextUploadingField(
        "Content", 
        )
    photo_1 = models.ImageField(
        "Photo 1", 
        upload_to="images/", 
        height_field=None, 
        width_field=None, 
        max_length=None,
        null = False,
        blank= False,
        )
    photo_2 = models.ImageField(
        "Photo 2", 
        upload_to="images/", 
        height_field=None, 
        width_field=None, 
        max_length=None,
        null = True,
        blank= True,
        )
    photo_3 = models.ImageField(
        "Photo 3", 
        upload_to="images/", 
        height_field=None, 
        width_field=None, 
        max_length=None,
        null = True,
        blank= True,
        )
    video_1 = models.FileField(
        "Video 1", 
        upload_to="videos/", 
        max_length=100,
        null = True,
        blank= True,
        )
    video_2 = models.FileField(
        "Video 2", 
        upload_to="videos/", 
        max_length=100,
        null = True,
        blank= True,
        )
    anexos = models.CharField(
        "Anexos", 
        max_length=50
        )
    code = models.URLField(
        "Code", 
        max_length=200, 
        unique = True
        )

    languages = models.ManyToManyField(languages)

    frameworks = models.ManyToManyField(framework)

    hardware = models.ManyToManyField(hardware)


    public = models.BooleanField(
        "Public", 
        default=True
        )
    Favorite = models.BooleanField(
        "Favorite", 
        default=False
        )

    class Meta:
        verbose_name = "Project"
        verbose_name_plural = "Projects"
    
    def __str__(self):
        return f"{self.id} | {self.title}"

    objects = ProjectsManager()

class dependency(models.Model):

    """Model definition for dependency."""

    name = models.CharField(
        "Name", 
        max_length=100, 
        null=False
        )
    country = models.CharField(
        "Country", 
        max_length=50
        )
    city = models.CharField(
        "City", 
        max_length=50
        )
    email = models.EmailField(
        "E-mail", 
        max_length=254
        )
    address = models.CharField(
        "Adress", 
        max_length=100
        )
    phone = models.CharField(
        "Phone", 
        unique=True,
        max_length=20
        )

    class Meta:
        """Meta definition for dependency."""

        verbose_name = 'Dependency'
        verbose_name_plural = 'Dependencies'

    def __str__(self):
        """Unicode representation of dependency."""
        return f"{self.id} | {self.name}"


class rewards(models.Model):
    """Model definition for Rewards."""

    name = models.CharField(
        "Name", 
        max_length=50, 
        unique=True
        )
    date = models.DateField(
        "Date", 
        auto_now=False, 
        auto_now_add=False
        )
    dependency_name = models.ForeignKey(
        dependency, 
        on_delete=models.CASCADE
        )
    link = models.URLField("Link", max_length=200, blank = True)
    
    class Meta:
        """Meta definition for Rewards."""

        verbose_name = 'Reward'
        verbose_name_plural = 'Rewards'

    def __str__(self):
        """Unicode representation of Rewards."""
        return f"{self.id} | {self.name}"

applications/projects/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import projects, languages
from django.utils import timezone
# Create your views here.



class ProjectsListView(ListView):
    model = projects
    template_name = "projects/list.html"
    context_object_name = 'projects'
    paginate_by = 4
    ordering = 'id'
    
    def get_context_data(self, **kwargs):
        context = super(ProjectsListView, self).get_context_data(**kwargs)
        context["languages"] = languages.objects.all()
        
        categories={}
        for category in projects.CATEGORY_CHOICES[:]:
            categories.update({category[0]:category[1]})
        zipCat = zip(categories.values(), categories.keys())
        context["categories"] = zipCat
        return context
    
    def get_queryset(self):
        kword = self.request.GET.get("kword", "")
        category = self.request.GET.get("category", "")
        language = self.request.GET.get("language", "")
        # Consulta de busqueda
        resultado = projects.objects.find_project(kword, category, language)
        return resultado
    

class ProjectsDetailView(DetailView):
    model = projects
    template_name = "projects/detail.html"
    context_object_name = 'projects'
    
    

templates/projects/base_projects.html
{% extends 'base.html' %}

{% load  static %}


{% block css %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">-->
    <link rel="stylesheet" href="../../static/css/style.css"> 
    <link rel="stylesheet" href="../../static/css/colors.css"> 
 
{% endblock css %}


{% block js %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script> 
    <!-- <script src="../../static/js/bootstrap.bundle.js"></script> -->
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
{% endblock js %}
    

templates/projects/detail.html
{% extends 'projects/base_projects.html' %}

{% load static %}


{% block title %}
    {{projects.title.title}}
{% endblock title %}


{% block content %}
  {% include 'includes/header.html' %}
  <div class="container">
    
    <div class="col-12 m-3 p-2 color1 color3back d-flex justify-content-center " style="border-radius: 20px;"><h1>{{projects.title.title}}</h1></div>
    
    <div class="row">
      <div class="col-5 col-md-8 m-1"><li>{{projects.get_category_display}}</li></div>

      <div class="col-5 col-md-3 m-1 font-italic text-muted"><ul>'{{projects.date}}'</ul></div>
    </div>

    <div><h4>{{projects.resume}}</h4></div>
    <br><br>
    <div class="container d-flex justify-content-center "><p>
      |=======================================|
    </p>  
    </div>
    
    <br><br><br>
    <div class="row border border-4 border-dark">
    <div class="col-md-8"><p>{{projects.contenido|safe}}</p></div>

    <div class="col-md-4 m-0">
      {% if projects.photo_1 %}
      <div><p><img src="{{projects.photo_1.url}}" height="300" width="360" class="shadow-lg mb-1 bg-body rounded img-fluid" title="photo_1"></p></div>
      {% else %}
      <div></div>
      {% endif %}
      
      {% if projects.photo_2 %}
      <div><p><img src="{{projects.photo_2.url}}" height="300" width="360" class="shadow-lg mb-1 bg-body rounded img-fluid" title="photo_2"></p></div>
      {% else %}
      <div></div>
      {% endif %}
        
      {% if projects.photo_3 %}
      <div><p><img src="{{projects.photo_3.url}}" height="300" width="360" class="shadow-lg mb-1 bg-body rounded img-fluid" title="photo_3"></p></div>
      {% else %}
      <div></div>
      {% endif %}
    </div>
  </div>

    {% if projects.video_1 %}
    <div><p><video src="{{projects.video_1.url}}" controls height="520" width="1024" class="col-12 rounded m-3"></video></p></div>
    {% else %}
    <div></div>
    {% endif %}

    {% if projects.video_2 %}
    <div><p><video src="{{projects.video_2.url}}" controls height="520" width="720"></video></p></div>
    {% else %}
    <div></div>
    {% endif %}

    <div class="col-12 d-flex justify-content-center m-2"><p>{{projects.anexos}}</p></div>

    <div class="col-12 d-flex justify-content-center m-2"><p><a href="{{projects.code}}" class="alert-link">Repositorio Git</a></p></div>
    
    <!--
      Features used
    -->

    <div class="container">
      <div class="row">
        <div class="col col-md-4">
          <h3>Languages used:</h3>
          {% for language in projects.languages.all %}
          <ul>
            <li><em>{{language.name}}</em></li>
          </ul>
          {% endfor %}
        </div>
        <div class="col col-md-4">
          <h3>Frameworks used:</h3>
          {% for framework in projects.frameworks.all %}
          <ul>
            <li><em>{{framework.name}}</em></li>
          </ul>            
          {% endfor %}  
        </div>
        <div class="col col-md-4">
          <h3>Hardware used:</h3>
          {% for hardware in projects.hardware.all %}
          <ul>
            <li><em>{{hardware.name}}</em></li>
          </ul>
          {% endfor %}  
        </div>
      </div>
    </div>
  </div>
    
   
{% include 'includes/footer.html' %}    
        

{% endblock content %}
    
    

templates/projects/list.html
{% extends 'projects/base_projects.html' %}

{% load static %}


{% block title %}
    Projects list
{% endblock title %}
    

{% block content %}

{% include 'includes/header.html' %}
<!-- Buscador  -->
<div class="container">
    <nav class="navbar navbar-light" style="background-color: rgba(201, 164, 125, 0.705);">
        <div class="container-fluid col-md-8 col-sm-5 col-8">
            <form class="d-flex" method="GET">{% csrf_token %}
            <input class="form-control me-2 m-1" type="search" placeholder="Search by Title" aria-label="Search" id="kword" name="kword">
            <button class="btn btn-outline-dark m-auto" type="submit">Search</button>
            </form>
        </div>
            <!-- Language by list -->
            <div class="dropdown col-md-2 col-sm-3 col-12 d-flex justify-content-center">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="True">Languages</button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
                    {% for language in languages %}  
                        <li><a href="?language={{ language.name }}" class="dropdown-item" name="language" id="language">{{language.name}}</a></li>   
                    {% endfor %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a href="{% url 'projects_app:projects-list' %}" class="dropdown-item">All</a></li>   
                </ul>
            </div>
            <!-- Categories by list -->
            <div class="dropdown col-md-2 col-sm-3 col-12 d-flex justify-content-center">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="True">
                Category
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">

                    {% for value,key in categories %}

                        <li><a href="?category={{ key }}" class="dropdown-item" name="category" id="category">{{value}}</a></li>

                    {% endfor %}

                        <li><hr class="dropdown-divider"></li>
                        <li><a href="{% url 'projects_app:projects-list' %}" class="dropdown-item">All</a></li>   
                </ul>
            </div>
            
    </nav>
</div>

<!-- New Card -->
<h1 style="text-align: center; font-family: Garamond; font-family: Aesthetic Violet;" class="container pt-4 color2">Projects</h1>

<section class="wrapper">
  {% for project in projects %}
  <a href="{% url 'projects_app:project-detail' project.id %}"></a>

    <div class="container">
      <div class="row">
        
        
        <div class="col-sm-7 col-lg-4 m-auto">
          <div class="card text-white card-has-bg click-col m-2" style="background-image:url({{project.photo_1.url}});">
            <img class="card-img d-none" src="{{project.photo_1.url}}" alt="Goverment Lorem Ipsum Sit Amet Consectetur dipisi?">
            <div class="card-img-overlay d-flex flex-column">
              <div class="card-body">
                <small class="card-meta mb-2">{{project.title.title}}</small>
                <h4 class="card-title mt-0 "><a class="text-white" herf="{% url 'projects_app:project-detail' project.id %}">{{project.resume|truncatechars:65}}</a></h4>
                <small>{{project.date}}</small>
                <small class="far fa-clock row d-flex justify-content-end color5"><i>Tag: {{project.get_category_display}}</i></small>
                <div class="row d-flex justify-content-center">
                <a href="{% url 'projects_app:project-detail' project.id %}" class="btn colorbotton text-center m-auto">Read More</a>
                </div>
              </div>
              <div class="container card-footer">
                <div class="media">
                  <img class="mr-3 rounded-circle" src="../../static/img/Universum Fiesta CyT.jpg" alt="Generic placeholder image" style="max-width:50px">
                  <div class="media-body col-8">
                    <h6 class="my-0 text-white d-block">Aarón Juárez</h6>
                    <small>Contact me</small> 
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        
        {% empty %}
        <h3 style="color: brown; font-family: Aesthetic Violet;" class="container row d-flex justify-content-center m-3">There aren't results</h3>
        {% endfor %}

        

  
      </div>
  
    </div>
    </a>

  </section>
  <br>

<!-- Projects realized list -->
<!--
<div>
    <h1 style="text-align: center; font-family: Garamond; font-family: Aesthetic Violet;" class="container pt-4 color2">Projects</h1>

    {% for project in projects %}

    <div class="p-3 container d-flex">
            <article class=" card d-flex justify-content-center shadow color1back" style="width: 45em; margin: auto;">
                <div class="card-body row">
                    <h5 class="card-title col-4 rounded color1back color1" style="font-family: Aesthetic Violet;">{{project.title.title}}</h5>
                    <img src="{{project.photo_1.url}}" class="card-img-bottom col-8 image-fluid" style="border-radius: 5em;" width="1080" height="320">
                </div>
                <div class="row">
                    <p class="card-text col-9 m-2" style="text-align: justify;">{{project.resume| truncatechars:150}}</p>
                    <p class="card-text col-2 color5back m-3" style="border-radius: 20px;">Tag: <i>{{project.get_category_display}}</i></p>
                </div>
                <div class="row d-flex justify-content-center">
                    <a href="{% url 'projects_app:project-detail' project.id %}" class="btn colorbotton text-center col-3 m-3">Read More</a>
                </div>
               
            </article>
    </div>
        
    {% empty %}
    <h3 style="color: brown; text-align: center; padding: 20px; font-family: Aesthetic Violet;">There aren't results</h3>
    {% endfor %}
    -->
    
    <!-- Pagination -->
    <nav aria-label="..."  class="container d-flex justify-content-center">
        <ul class="pagination pagination-sm">
        
        <!-- Previous page -->
        
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}" aria-label="Previous">
               <span aria-hidden="true"><ion-icon name="arrow-undo-circle-outline"></ion-icon></span>
            </a>
        </li>    
        {% endif %}
            
        
        <!-- Number of pages -->

        {% for pagina in paginator.page_range %}
        
        {% ifequal pagina page_obj.number  %} 
            <li class="page-item active" aria-current="page">
                <span class="page-link">{{pagina}}</span>
            </li>
        {% else %}
            <li class="page-item"><a class="page-link" href="?page={{pagina}}" aria-label="{{pagina}}">{{pagina}}</a></li>
        {% endifequal %}
            
        {% endfor %}
        
        <!-- Next page -->
        
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
                <ion-icon name="arrow-redo-circle-outline" style="font-size: 16px;"></ion-icon>
            </a>
        </li>    
        {% endif %}
            
        

        </ul>
    </nav>
    

{% include 'includes/footer.html' %}


{% endblock content %}
    