Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.projects.urls')),
    path('', include('applications.home.urls')),
    path('', include('applications.users.urls')),

    # urls para ckeditor
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/home/urls.py
from django.urls import path
from . import views

app_name = "home_app"

urlpatterns = [
    path(
        "",
        views.HomePage.as_view(),
        name="home_page",
    ),
    path(
        "about/",
        views.AboutMe.as_view(),
        name="about_me",
    ),


]

applications/projects/urls.py
from django.urls import path
from . import views

app_name = "projects_app"

urlpatterns = [
    path(
        "projects/",
        views.ProjectsListView.as_view(),
        name="projects-list",
    ),
    path(
        "projects/<pk>/",
        views.ProjectsDetailView.as_view(),
        name="project-detail",
    )


]

applications/users/urls.py
from django.urls import path
from . import views

app_name = "users_app"

urlpatterns = [
    path(
        "contact/",
        views.ContactCreateView.as_view(),
        name="contact",
    ),

]

templates/includes/footer.html
    <div class="footer-basic" style="background-color: rgba(235, 224, 212, 0.918);">
        <footer>
            <div class="social">
                <a href="{% url 'projects_app:projects-list' %}"><ion-icon name="logo-python"></ion-icon></a>
            </div>
            <div class="social">
                <a href="https://hub.docker.com/u/aaronga19"><ion-icon name="logo-docker"></ion-icon></a>
                <a href="https://www.linkedin.com/in/aar%C3%B3n-ju%C3%A1rez-6298561a4/"><ion-icon name="logo-linkedin"></ion-icon></a>
                <a href="https://github.com/Aaronga19"><ion-icon name="logo-github"></ion-icon></a>
                <a href="https://es.stackoverflow.com/users/201799/aaron-acosta"><ion-icon name="logo-stackoverflow"></ion-icon></a>
            </div>
            <ul class="list-inline">
                <li class="list-inline-item"><a href="{% url 'home_app:home_page' %}">Home</a></li>
                <li class="list-inline-item"><a href="{% url 'projects_app:projects-list' %}">Projects</a></li>
                <li class="list-inline-item"><a href="{% url 'home_app:about_me' %}">About me</a></li>
                <li class="list-inline-item"><a href="{% url 'users_app:contact' %}">Contact</a></li>
                <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
            </ul>
            <p class="copyright">Aaron's Portfolio © 2021</p>
        </footer>
    </div>
    

templates/includes/header.html
<header>
    <!-- Bootstrap Static Header -->
  <div style="background: url(../../static/img/wallpapert_tec.jpg)" class="jumbotron bg-cover text-white">
    
    <!-- Nav -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark m-auto container-fluid justify-content-center" style="border-radius: 20px; width: 80%;">
        <a class="navbar-brand" href="#" style="font-family: Aesthetic Violet;">
          <img src="../../static/img/portfoliored.svg" width="30" height="30" class="d-inline-block align-top" title="portfolio">
          Porfolio
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/' %}active{% endif %} " href="{% url 'home_app:home_page' %}" style="font-family: Aesthetic Violet;">Home <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/projects/' %}active{% endif %}" href="{% url 'projects_app:projects-list' %}" style="font-family: Aesthetic Violet;">Projects <span class="sr-only"></span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/about/' %}active{% endif %}" href="{% url 'home_app:about_me' %}" style="font-family: Aesthetic Violet;">About Me</a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if request.path == '/contact/' %}active{% endif %}" href="{% url 'users_app:contact' %}" style="font-family: Aesthetic Violet;">Contact</a>
            </li>
          
          </ul>
        </div>
      </nav>
    <!--Titulo-->
    <div class="container py-5 text-center">
        <h1 class="display-4 font-weight-bold mainfont" style="font-family: Aesthetic Violet; color: bisque;">Aarón Juárez</h1>
        <p class="font-italic m-3"><h4 style="color: rgb(224, 191, 150);">Backend Developer & Data Scientist.</h4></p>
        <p class="font-italic"><cite style="color: rgb(224, 191, 150);">Let's keep learning</cite>
            <!-- <a href="https://www.unam.mx/" class="text-white" style="font-family: Aesthetic Violet; color: bisque;">
                <p>
                  <u>UNAM</u>
                </p>
            </a> -->
        </p>
        <a href="{% url 'projects_app:projects-list' %}" role="button" class="btn colorbottonHead px-5" style="font-family: Aesthetic Violet;">See Projects</a>
    </div>
  </div>
</header>